using Cryptid.Domain.Enums;

namespace Cryptid.Domain.PlayerRules
{
    public static class GammaRules
    {
        public static Dictionary<int, Rule> Get() => new()
        {
            { 1, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlueStandingStone, IconTwo = RuleIcon.BlueAbandonedShack } },
            { 2, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Water } },
            { 3, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Mountain } },
            { 4, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Swamp } },
            { 5, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Water } },
            { 6, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlueStandingStone, IconTwo = RuleIcon.BlueAbandonedShack } },
            { 7, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Desert } },
            { 8, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Swamp } },
            { 9, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Water } },
            { 10, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.StandingStone } },
            { 11, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.GreenStandingStone, IconTwo = RuleIcon.GreenAbandonedShack } },
            { 12, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.StandingStone } },
            { 13, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Water } },
            { 14, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlackStandingStone, IconTwo = RuleIcon.BlackAbandonedShack } },
            { 15, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Swamp } },
            { 16, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.StandingStone } },
            { 17, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Mountain } },
            { 18, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Mountain } },
            { 19, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Swamp } },
            { 20, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Swamp } },
            { 21, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Desert } },
            { 22, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Desert } },
            { 23, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Mountain } },
            { 24, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Swamp } },
            { 25, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlackStandingStone, IconTwo = RuleIcon.BlackAbandonedShack } },
            { 26, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlueStandingStone, IconTwo = RuleIcon.BlueAbandonedShack } },
            { 27, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Forest } },
            { 28, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.WhiteStandingStone, IconTwo = RuleIcon.WhiteAbandonedShack } },
            { 29, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.AnimalTerritory } },
            { 30, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.WhiteStandingStone, IconTwo = RuleIcon.WhiteAbandonedShack } },
            { 31, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Swamp } },
            { 32, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Swamp, IconTwo = RuleIcon.Mountain } },
            { 33, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Swamp } },
            { 34, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.GreenStandingStone, IconTwo = RuleIcon.GreenAbandonedShack } },
            { 35, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.GreenStandingStone, IconTwo = RuleIcon.GreenAbandonedShack } },
            { 36, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Forest } },
            { 37, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Water } },
            { 38, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.BearTerritory } },
            { 39, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Mountain } },
            { 40, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.WhiteStandingStone, IconTwo = RuleIcon.WhiteAbandonedShack } },
            { 41, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Mountain } },
            { 42, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlueStandingStone, IconTwo = RuleIcon.BlueAbandonedShack } },
            { 43, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Mountain } },
            { 44, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.BearTerritory } },
            { 45, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Swamp } },
            { 46, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Forest } },
            { 47, new() { RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlackStandingStone, IconTwo = RuleIcon.BlackAbandonedShack } },
            { 48, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Swamp } },
            { 49, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.CougarTerritory } },
            { 50, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.CougarTerritory } },
            { 51, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Swamp, IconTwo = RuleIcon.Mountain } },
            { 52, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.BearTerritory } },
            { 53, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.AnimalTerritory } },
            { 54, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.BearTerritory } },
            { 55, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Mountain } },
            { 56, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Swamp } },
            { 57, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Mountain } },
            { 58, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.AnimalTerritory } },
            { 59, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Water } },
            { 60, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Mountain } },
            { 61, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Desert } },
            { 62, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Water } },
            { 63, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.StandingStone } },
            { 64, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Swamp, IconTwo = RuleIcon.Mountain } },
            { 65, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.AbandonedShack } },
            { 66, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Swamp } },
            { 67, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Mountain } },
            { 68, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Desert } },
            { 69, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.CougarTerritory } },
            { 70, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Water, IconTwo = RuleIcon.Swamp } },
            { 71, new() { RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.AbandonedShack } },
            { 72, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.GreenStandingStone, IconTwo = RuleIcon.GreenAbandonedShack } },
            { 73, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Water } },
            { 74, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Desert } },
            { 75, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.AnimalTerritory } },
            { 76, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Forest } },
            { 77, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Mountain } },
            { 78, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.AbandonedShack } },
            { 79, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Mountain } },
            { 80, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Mountain } },
            { 81, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Desert } },
            { 82, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Water } },
            { 83, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.AbandonedShack } },
            { 84, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Swamp } },
            { 85, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Water } },
            { 86, new() { IsInverse = true, RuleGroup = RuleGroup.WithinTwoSpaces, IconOne = RuleIcon.CougarTerritory } },
            { 87, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Water } },
            { 88, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.BlackStandingStone, IconTwo = RuleIcon.BlackAbandonedShack } },
            { 89, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Forest, IconTwo = RuleIcon.Swamp } },
            { 90, new() { IsInverse = true, RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Mountain } },
            { 91, new() { IsInverse = true, RuleGroup = RuleGroup.WithinThreeSpaces, IconOne = RuleIcon.WhiteStandingStone, IconTwo = RuleIcon.WhiteAbandonedShack } },
            { 92, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Desert, IconTwo = RuleIcon.Water } },
            { 93, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Mountain } },
            { 94, new() { RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Swamp } },
            { 95, new() { IsInverse = true, RuleGroup = RuleGroup.WithinOneSpace, IconOne = RuleIcon.Desert } },
            { 96, new() { RuleGroup = RuleGroup.OneOfTwo, IconOne = RuleIcon.Swamp, IconTwo = RuleIcon.Mountain } },
        };
    }
}
